server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Prevent large header issues
    client_header_buffer_size 64k;
    large_client_header_buffers 4 64k;


    # Backend API routes
    # /api/create  ->  backend /create
    # /api/update/1 -> backend /update/1
    # /api/1 -> backend /1
    # /api/ -> backend /
    location /api/ {
        proxy_pass http://192.168.1.69:8080/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }


    # React frontend
    location / {
        try_files $uri /index.html;
    }
}
