when:
  event:
    - push
  branch:
    - main

steps:
  deploy:
    image: docker:27-cli

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    commands:
      - docker compose up -d --build --remove-orphans
      - docker image prune -f
