services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./server

    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

  frontend:
    build:
      context: ./client

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  mysql_data:
