services:
  mysql:
    image: mysql:8.4
    container_name: todo-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ./mysql:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: server.Dockerfile

    container_name: todo-backend

    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

  frontend:
    build:
      context: .
      dockerfile: client.Dockerfile

    container_name: todo-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"
